KIITCSITTISCTIIK
KIITCSI ISCTIIK
KIITCS   SCTIIK
KIITC     CTIIK
KIIT       TIIK
KII         IIK
KI           IK
K             K
KI           IK
KII         IIK
KIIT        TIIK
KIITC CTIIK
KIITCS SCTIIK
KIITCSI ISCTIIK
KIITCSITTISCTIIK